- name: Install base packages
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  notify:
    - Enable REMI

- meta: flush_handlers

- name: Install apache packages
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - httpd
    - php
    - php-mysql
    - php-pecl-zip
    - php-xml
    - php-mbstring
    - php-gd
    - php-ldap
    - php-process
    - php-mcrypt
    - mod_ssl
    - php-xml
    - php-php-gettext

- name: Configure php
  template:
    src:   etc/php.ini
    dest: /etc/php.ini

- name: Setup service
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - httpd

- name: Ensure firewall is running
  service:
    name: firewalld
    state: started
    enabled: true

- name: Setup firewall
  firewalld:
    service: '{{ item }}'
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - http
    - https
